//! Export adapters — render the working set into formats other agent
//! tools understand.
//!
//! Every adapter is a pure function `&[MemoryNode] → String`. The
//! [`crate::repo::Repository`] handles ranking and filtering before
//! handing the nodes here, so the adapters stay focused on formatting.

use std::fmt::Write as _;

use serde::Serialize;

use crate::node::{MemoryKind, MemoryNode, MemoryStatus};

/// Supported export targets.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    /// `CLAUDE.md` — long-form markdown, project-aware sections.
    ClaudeCode,
    /// `.cursorrules` — terse rule list, no headings.
    Cursor,
    /// `.clinerules` — markdown bullet list with kind tags.
    Cline,
    /// JSON object suitable for the OpenAI Assistants API `instructions`
    /// field, plus a structured `memories` array.
    OpenAiAssistant,
    /// Raw JSON — every node serialised in full. Round-trippable.
    Json,
}

impl ExportFormat {
    /// Parse a CLI string. Accepts both kebab and snake case.
    pub fn parse(s: &str) -> Option<Self> {
        Some(match s.to_ascii_lowercase().as_str() {
            "claude-code" | "claude_code" | "claudecode" => ExportFormat::ClaudeCode,
            "cursor" | "cursorrules" => ExportFormat::Cursor,
            "cline" | "clinerules" => ExportFormat::Cline,
            "openai-assistant" | "openai_assistant" | "openai" => ExportFormat::OpenAiAssistant,
            "json" => ExportFormat::Json,
            _ => return None,
        })
    }

    /// Conventional output filename for this format.
    pub fn default_filename(self) -> &'static str {
        match self {
            ExportFormat::ClaudeCode => "CLAUDE.md",
            ExportFormat::Cursor => ".cursorrules",
            ExportFormat::Cline => ".clinerules",
            ExportFormat::OpenAiAssistant => "openai-assistant.json",
            ExportFormat::Json => "memora-export.json",
        }
    }
}

/// Render a sorted set of nodes into the requested format. The caller is
/// responsible for sorting / filtering / capping before this is called.
pub fn render(format: ExportFormat, nodes: &[MemoryNode]) -> String {
    match format {
        ExportFormat::ClaudeCode => render_claude_code(nodes),
        ExportFormat::Cursor => render_cursor(nodes),
        ExportFormat::Cline => render_cline(nodes),
        ExportFormat::OpenAiAssistant => render_openai_assistant(nodes),
        ExportFormat::Json => render_json(nodes),
    }
}

fn render_claude_code(nodes: &[MemoryNode]) -> String {
    let mut out = String::new();
    out.push_str("# Project memory (exported from memora)\n\n");
    out.push_str(
        "_This file is generated by `memora export --to=claude-code`. Edit your memora\n\
         store and re-export rather than editing this file by hand._\n\n",
    );

    if nodes.is_empty() {
        out.push_str("_(no memories yet)_\n");
        return out;
    }

    for kind in MemoryKind::ALL {
        let bucket: Vec<&MemoryNode> = nodes.iter().filter(|n| n.kind == kind).collect();
        if bucket.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## {}\n", title_case(kind.as_str()));
        for n in bucket {
            let _ = writeln!(out, "- {}", n.content);
            let mut footer = format!(
                "  _confidence {:.2} · {} · {}",
                n.confidence,
                n.status,
                n.source
            );
            if let Some(ev) = &n.evidence {
                footer.push_str(&format!(" · evidence: {ev}"));
            }
            if !n.tags.is_empty() {
                footer.push_str(&format!(" · tags: {}", n.tags.join(", ")));
            }
            footer.push('_');
            let _ = writeln!(out, "{footer}");
        }
        out.push('\n');
    }
    out
}

fn render_cursor(nodes: &[MemoryNode]) -> String {
    // .cursorrules is just a flat instruction list. We dump every
    // stable / ephemeral fact, drop deprecated and conflicted entries
    // (the user shouldn't be feeding those to a coding agent verbatim).
    let mut out = String::new();
    out.push_str("# memora export — cursor rules\n\n");
    for n in nodes {
        if matches!(n.status, MemoryStatus::Deprecated | MemoryStatus::Conflicted) {
            continue;
        }
        let _ = writeln!(out, "- [{}] {}", n.kind, n.content);
    }
    out
}

fn render_cline(nodes: &[MemoryNode]) -> String {
    let mut out = String::new();
    out.push_str("# memora export — cline rules\n\n");
    for n in nodes {
        let _ = writeln!(
            out,
            "- **{}** _(confidence {:.2}, {})_: {}",
            title_case(n.kind.as_str()),
            n.confidence,
            n.status,
            n.content,
        );
    }
    out
}

fn render_openai_assistant(nodes: &[MemoryNode]) -> String {
    #[derive(Serialize)]
    struct OpenAiExport<'a> {
        instructions: String,
        memories: Vec<OpenAiMemory<'a>>,
    }
    #[derive(Serialize)]
    struct OpenAiMemory<'a> {
        kind: &'a str,
        content: &'a str,
        confidence: f32,
        status: &'a str,
        source: String,
        evidence: Option<&'a String>,
        tags: &'a [String],
    }

    let mut instructions = String::from(
        "You have access to typed project memory. Treat `stable` items as confirmed facts and \
         `ephemeral` items as working assumptions to verify before acting on.\n\n",
    );
    for n in nodes.iter().take(8) {
        let _ = writeln!(instructions, "- [{}] {}", n.kind, n.content);
    }

    let memories: Vec<OpenAiMemory<'_>> = nodes
        .iter()
        .map(|n| OpenAiMemory {
            kind: n.kind.as_str(),
            content: &n.content,
            confidence: n.confidence,
            status: n.status.as_str(),
            source: n.source.as_str(),
            evidence: n.evidence.as_ref(),
            tags: &n.tags,
        })
        .collect();

    let payload = OpenAiExport {
        instructions,
        memories,
    };
    serde_json::to_string_pretty(&payload).unwrap_or_else(|e| format!("{{\"error\":\"{e}\"}}"))
}

fn render_json(nodes: &[MemoryNode]) -> String {
    serde_json::to_string_pretty(nodes).unwrap_or_else(|e| format!("[\"error\",\"{e}\"]"))
}

fn title_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}
